#ifndef NVC_H_
#define NVC_H_

#define SOUND_SYSTEM_SETTING 0
#define SOUND_VOICE_SETTING 1
#define SOUND_WIFI_CONFIG 2
#define SOUND_START_WIFI_CONFIG 3
#define SOUND_WIFI_CONFIG_SUCCESS 4
#define SOUND_WIFI_CONFIG_FAIL 5
#define SOUND_RECOVER_FACTORY_CONFIG 6
#define SOUND_USER_MANAGE 7
#define SOUND_ADD_GENERAL_USER 8
#define SOUND_ADD_ADMIN_USER 9
#define SOUND_EDIT_USER 10
#define SOUND_DELETE_USER 11
#define SOUND_DELETE_USER_SUCCESS 12
#define SOUND_INPUT_PASSWORD 13
#define SOUND_INPUT_PASSWORD_AGAIN 14
#define SOUND_LEAVE_FINGER 15
#define SOUND_PRESS_FINGER_PRINT_AGAIN 16
#define SOUND_PRESS_FINGER_VEIN_AGAIN 17
#define SOUND_USER_LIST_EMPTY 18
#define SOUND_OPERATION_SUCCESS 19
#define SOUND_OPERATION_FAIL 20
#define SOUND_TIME_SETTING 21
#define SOUND_CLICK1 22
#define SOUND_CLICK2 23
#define SOUND_WARNING1 24
#define SOUND_WARNING2 25
#define SOUND_DOOR_BELL 26
#define SOUND_FAIL1 27
#define SOUND_FAIL2 28
#define SOUND_TIP1 29
#define SOUND_TIP2 30
#define SOUND_CORRECT1 31
#define SOUND_CORRECT2 32


u8 playSound(u8 index, u8 waitFlag);
#endif